---
sudo: required
language: python
services:
  - docker
before_install:
  - sudo apt-get -qq update
install:
  - pip install molecule
  - pip install docker
script:
  - base=$PWD
  - for role in roles/k3s; do cd $role; molecule test; cd $base; done
