---
# defaults file for webshare
country: "DE"
state: "Bayern"
city: "Dachau"
cert_path: "/etc/ssl/certs"
key_path: "/etc/ssl/private"
vhost_ssl_only: yes
vhost_ssl_certificate: "{{ cert_path }}/{{ vhost_domain }}.pem"
vhost_ssl_key: "{{ key_path }}/{{ vhost_domain }}.key"
vhost_ssl_csr: "{{ cert_path }}/{{ vhost_domain }}.csr"
apache_var: "/var/apache2/2.4"
vhost_directory: "{{ apache_var }}/{{ vhost_domain }}"
apache_etc: "/etc/apache2/2.4"
httpd_conf: "{{ apache_etc }}/httpd.conf"
htpass_file: "{{ apache_etc }}/.htpasswd"
htdigest_file: "{{ apache_etc }}/.htdigest"
