---
# tasks file for common
- name: Add my ssh key
  authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ item }}"
  with_file:
    - "{{ ssh_pubkey_ed }}"

- name: Allow user to have passwordless sudo
  copy:
    dest: "/etc/sudoers.d/{{ ansible_user }}"
    content: '{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL'

- name: Install base packages
  include: "pkgs/{{ ansible_distribution }}.yml"

- name: configure NTP
  copy:
      dest: /etc/inet/ntp.conf
      content: |
        server 0.de.pool.ntp.org
        server 1.de.pool.ntp.org
        server 2.de.pool.ntp.org
        server 3.de.pool.ntp.org
        broadcastclient
        disable auth
        driftfile /var/ntp/ntp.drift
        filegen loopstats file loopstats type day enable
        filegen peerstats file peerstats type day enable
        statsdir /var/ntp/ntpstats/
  notify: Reload NTP
  tags: NTP
