---
- hosts: storage
  become: yes
  roles:
      - common
      - { role: storage, when: ansible_distribution == "Solaris", tags: storage }
      - { role: webshare, when: ansible_distribution == "Solaris", tags: webshare }

- hosts: homecenter
  become: yes
  roles:
      - common
